sudo: required
services:
  - docker

before-install:
  - docker build -t daimmuzaffer/docker-react -f Dockerfile.dev .

script:
  - docker run daimmuzaffer/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name:
  bucket_path: 
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY" 